spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saas_ecommerce
    username: postgres
    password: postgreSql123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
